
import {Room}from "./types";


export const ROOMS: Room[] =[
  {
    "model": "hotel.room",
    "pk": 1,
    "fields": {
      "category": "Luxe",
      "bedType": "King Size",
      "adults": 1,
      "children": 1, 
      "squareType": 25,
      "number": 101,
      "name_ru": "Султан Мухаммад Хорезмшах",
      "name_en": "SULTAN MUKHAMMAD KHORAZMSHAH ",
      "description_ru": "Султан Мухаммад Хорезмшах -- люкс с хорезмским калоритом! Посвященный ему номер с площадью _ квадратных метра перенесет вас в покои правителя Хорезма в 1200-1220 годах. Удобства в номере гарантированно создадут ваш заслуженный лучший отдых!",
      "description_en": "Sultan Mukhammad Khorezmshah - it’s a suite with Khorezm calorite! This room  with an area of _ square meters will take you to the chambers of the ruler of Khorezm in 1200-1220 years. The amenities in the room are guaranteed to create your well-deserved best vacation! ",
      "numberOfBeds": 2,
      "price": 1700000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_8655_YosCODk.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "001"
    }
  },
  {
    "model": "hotel.room",
    "pk": 2,
    "fields": {
      "category": "Luxe",
      "bedType": "Twin",
      "adults": 1,
      "children": 1, 
      "squareType": 36,
      "number": 102,
      "name_ru": "Туркан Хатун",
      "name_en": "TURKAN KHATUN",
      "description_ru": "Туркан Хатун - покои одной из самых известных женщин в истории Средней Азии. Она приходилась бабушкой хорезмшаху Джелал-ад-Дину. Истинный комфортный номер с площадью _ позволит вам почувствовать себя женщиной королевской семьи!",
      "description_en": "Turkan Khatun is the chamber of one of the most famous women in the history of Central Asia. She was the grandmother of Khorezm Shah Jalal-ad-Din. A true comfortable room with an area of _ will make you feel like a woman of the royal family!",
      "numberOfBeds": 2,
      "price": 2000000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_9673.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "002"
    }
  },
  {
    "model": "hotel.room",
    "pk": 3,
    "fields": {
      "category": "Luxe",
      "bedType": "Twin",
      "adults": 2,
      "children": 1, 
      "squareType": 45,
      "number": 103,
      "name_ru": "Джелал ад-Дин Мангуберди",
      "name_en": "JALLOLIDDIN MANGUBERDI",
      "description_ru": "Джелал ад-Дин Мангуберди — это комната, посвященная последнему хорезмшаху (с 1220 года) из династии Ануштегенидов. Он вошел в историю как талантливый полководец и главный достойный враг Чингисхана. Номер, в котором царит сильный и волевой дух правителя, позволит вам окунуться в атмосферу борца и почувствовать себя могущественным и сильным!",
      "description_en": "Jalal ad-Din Manguberdi is a room dedicated to the last Khorezm shah (since 1220) of the Anushtegenid dynasty. He went down in history as a talented commander and the main worthy enemy of Genghis Khan. The room, in which the strong and strong-willed spirit of the ruler reigns, will allow you to plunge into the atmosphere of a fighter and feel powerful and strong! ",
      "numberOfBeds": 2,
      "price": 2200000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_9634.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "003"
    }
  },
  {
    "model": "hotel.room",
    "pk": 4,
    "fields": {
      "category": "Luxe",
      "bedType": "King Size",
      "adults": 2,
      "children": 2, 
      "squareType": 25,
      "number": 104,
      "name_ru": "Сатук Богра-хану",
      "name_en": "SATUQ BUGHRAKHAN",
      "description_ru": "Номер , посвящённый Сатук Богра-хану — это покои с историей с середины 10 века! Он был правителем Кашгара из рода Караханов, а в 942 году смог основать Караханидское государство на тюркской территории. В номере, вас ждет невероятный дух правителя государства, полностью пропитанный многовековой историей!",
      "description_en": "The room dedicated to Satuq Bugrakhan is a room with a history from the middle of the 10th century! He was the ruler of Kashgar from the Karakhan family, and in 942 he was able to establish a Karakhanid state on the Turkic territory. In the room, you will find the incredible spirit of the ruler of the state, completely imbued with centuries-old history! ",
      "numberOfBeds": 2,
      "price": 1850000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_9673.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "004"
    }
  },
  {
    "model": "hotel.room",
    "pk": 5,
    "fields": {
      "category": "Luxe",
      "bedType": "King Size",
      "adults": 3,
      "children": 1, 
      "squareType": 24,
      "number": 105,
      "name_ru": "Исмаил Самани",
      "name_en": "ISMAIL SAMANI",
      "description_ru": "Исмаил Самани — великий эмир из династии Саманидов, основатель государства в Средней Азии. Величественный номер выполнен полностью в стиле властного правителя с неподражаемым дизайном. Каждый уголок номера полюбится вами и станет излюбленным местом для отдыха.",
      "description_en": "Ismail Samani is the great emir of the Samanid dynasty, the founder of the state in Central Asia. The majestic room is made entirely in the style of an imperious ruler with an inimitable design. Every corner of the room will be loved by you and will become a favorite place to relax. ",
      "numberOfBeds": 3,
      "price": 2300000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_8619_4CZxOEX.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "005"
    }
  },
  {
    "model": "hotel.room",
    "pk": 6,
    "fields": {
      "category": "Deluxe",
      "bedType": "King Size",
      "adults": 3,
      "children": 0, 
      "squareType": 35,
      "number": 201,
      "name_ru": "Александр Македонский",
      "name_en": "ALEXANDR THE GREAT ",
      "description_ru": "Покои царя древней Македонии - Александр Македонского. Он был выдающимся полководецем, создателем мировой державы. Номер с площадью _ квадратных метров пропитан историей и духом древности, вмещая в себе все самые лучшие удобства. Проведите лучший отдых вместе с нами!",
      "description_en": "The chambers of the king of ancient Macedonia - Alexander the Great. He was an outstanding commander, the creator of the world power. The room with an area of _ square meters is imbued with history and the spirit of antiquity, accommodating all the best amenities. Spend the best vacation with us! ",
      "numberOfBeds": 2,
      "price": 1200000,
      "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_8514_EPoqzG1.JPG.1024x1024_q85.jpg",
      "air_conditioner": true,
      "bad": true,
      "bathrobe": true,
      "dressing_table": true,
      "kettle": true,
      "slippers": true,
      "table_lamp": true,
      "telephone": true,
      "tv": true,
      "wifi": true,
      "armchair": true,
      "mini_bar": true,
      "electric_power": true,
      "shower": true,
      "bath": true,
      "bath_with_shower": true,
      "beRoomType": "006"
    }
  },
  {
  "model": "hotel.room",
  "pk": 7,
  "fields": {
    "category": "Deluxe",
    "bedType": "Twin",
    "adults": 1,
    "children": 2, 
    "squareType": 54,
    "number": 202,
    "name_ru": "Роксана",
    "name_en": "ROXANA",
    "description_ru": "Роксана — бактрийская принцесса, жена Александра Македонского. В уютном и удобном номере каждая сможет почувствовать себя принцессой, ведь роскошный дизайн, мягкая кровать, а также все необходимые принадлежности для лучшего отдыха, который вы заслуживаете, ждет вас!",
    "description_en": "Roxana is a Bactrian princess, the wife of Alexander the Great. In a cozy and comfortable room, everyone can feel like a princess, because a luxurious design, a soft bed, as well as all the necessary accessories for the best rest that you deserve are waiting for you! ",
    "numberOfBeds": 2,
    "price": 1150000,
    "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_8625_haOkBAh.JPG.1024x1024_q85.jpg",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "bath": false,
    "bath_with_shower": true,
    "beRoomType": "007"
  }
},
{
  "model": "hotel.room",
  "pk": 8,
  "fields": {
    "category": "Deluxe",
    "bedType": "Twin",
    "adults": 2,
    "children": 0, 
    "squareType": 32,
    "number": 203,
    "name_ru": "Спитамен",
    "name_en": "SPITAMEN",
    "description_ru": "Спитамен — это мудрый и умелый согдийский военачальник, представитель согдийской аристократии. Мы посвятили номер с площадью _ квадратных метров самому смелому и воинственному противнику Александра Македонского. Атмосфера номера сможет перенести вас во времена древней истории и каждая минута пребывания будет незабываемой!",
    "description_en": "Spitamen is a wise and skillful Sogdian military commander, a representative of the Sogdian aristocracy. We dedicated a room with an area of _ square meters to the most courageous and militant opponent of Alexander the Great. The atmosphere of the room will be able to take you back to the times of ancient history and every minute of your stay will be unforgettable! ",
    "numberOfBeds": 2,
    "price": 1100000,
    "historicalImage": "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "bath": false,
    "bath_with_shower": true,
    "beRoomType": "008"
  }
},
{
  "model": "hotel.room",
  "pk": 9,
  "fields": {
    "category": "Deluxe",
    "bedType": "Twin",
    "adults": 2,
    "children": 2,
    "squareType": 45,
    "number": 204,
    "name_ru": "Томарис",
    "name_en": "TOMARIS",
    "description_ru": "Томарис - самая храбрая женщина-полководец древней истории, которая смогла возглавить туранский народ против завоевателей. Покои выдающейся волевой женщины завораживают сразу с самого порога. Просторный номер с прекрасным видом позволит вдоволь насладиться своим отдыхом!",
    "description_en": "Tomaris is the bravest female commander of ancient history, who was able to lead the Turanian people against the conquerors. The chambers of an outstanding strong-willed woman fascinate right from the very threshold. A spacious room with a beautiful view will allow you to enjoy your vacation! ",
    "numberOfBeds": 2,
    "price": 1350000,
    "historicalImage": "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "bath": true,
    "bath_with_shower": true,
    "beRoomType": "009"
  }
},
{
  "model": "hotel.room",
  "pk": 10,
  "fields": {
    "category": "Deluxe",
    "bedType": "King Size",
    "adults": 3,
    "children": 0,
    "squareType": 25,
    "number": 205,
    "name_ru": "Канишка III",
    "name_en": "KANISHKA III",
    "description_ru": "Канишка III - третий император Кушанского царства. Древняя история правителя позволила нам создать номер, пропитанный его неукратимым духом. Царские покои позволят вамкак следует отдохнуть после насыщенного дня, а время пребывания станет незабываемым",
    "description_en": "Kanishka III is the third emperor of the Kushan Kingdom. The ancient history of the ruler allowed us to create a room imbued with his indomitable spirit. The royal chambers will allow you to relax after a busy day, and your stay will be unforgettable. ",
    "numberOfBeds": 3,
    "price": 1400000,
    "historicalImage": "https://silkroadempirehotel.com/media/room_images/SRE_-_312_Amir_Temur_siute_-_4.JPG.1024x1024_q85.jpg",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "bath": true,
    "bath_with_shower": true,
    "beRoomType": "010"
  }
},
{
  "model": "hotel.room",
  "pk": 11,
  "fields": {
    "category": "Luxe",
    "bedType": "King Size",
    "adults": 1,
    "children": 0,
    "squareType": 65,
    "number": 301,
    "name_ru": "Зороастр",
    "name_en": "ZOROASTER",
    "description_ru": "Заратуштра, Зороастр — это основатель зороастризма: второй из известных монотеистических религий. Он также был жрецом и пророком, которому приписывается авторство Авесты — священного писания зороастризма. Номер оформлен в истории древней античности: каждый метр имеет дизайн близкий к атмосфере того периода, а современные удобства позволят совместить историю и прекрасный отдых!",
    "description_en": "Zarathustra, Zoroaster is the founder of Zoroastrianism: the second of the famous monotheistic religions. He was also a priest and a prophet, to whom the authorship of the Avesta, the holy scripture of Zoroastrianism, is attributed. The room is decorated in the history of ancient antiquity: each meter has a design close to the atmosphere of that period, and modern amenities will allow you to combine history and a wonderful vacation! ",
    "numberOfBeds": 2,
    "price": 2500000,
    "historicalImage": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "011"
  }
},
{
  "model": "hotel.room",
  "pk": 12,
  "fields": {
"category": "Luxe",
    "bedType": "Twin",
    "adults": 2,
    "children": 0,
    "squareType": 24,
    "number": 302,
    "name_ru": "Анахита",
    "name_en": "ANAHITA",
    "description_ru": "Номер, посвященный Ардвисуре Анахите, создаст для вас отдых истинных богин! Ведь героиня этого номера была богиней воды и плодородия в иранской мифологии. Невероятное величие покоев перенесет вас в атмосферу древней античности и обеспечат лучшее пребывание в городе Самарканд!",
    "description_en": "The room dedicated to Ardvisura Anahita will create for you the rest of true goddesses! After all, the heroine of this number was the goddess of water and fertility in Iranian mythology. The incredible greatness of the chambers will take you into the atmosphere of ancient antiquity and ensure the best stay in the city of Samarkand! ",
    "numberOfBeds": 2,
    "price": 2700000,
    "historicalImage": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "012"
  }
},
{
  "model": "hotel.room",
  "pk": 13,
  "fields": {
    "category": "Luxe",
    "bedType": "Twin",
    "adults": 1,
    "children": 3,
    "squareType": 32,
    "number": 303,
    "name_ru": "Вархуман",
    "name_en": "VARHUMAN",
    "description_ru": "Вархуман был царем Согдианы в 7 веке нашей эры. Мы посвятили ему номер с площадью _ квадратных метров, который буквально наполнен историей одного из самого великого царя античности. Уютный и в то же время просторный номер окружит вас отдыхом, который вы точно запомните надолго!",
    "description_en": "Varhuman was the king of Sogdiana in the 7th century. We dedicated to him a room with an area of _ square meters, which is literally filled with the history of one of the greatest kings of antiquity. A cozy and at the same time spacious room will surround you with a vacation that you will definitely remember for a long time!",
    "numberOfBeds": 2,
    "price": 2100000,
    "historicalImage": "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "013"
  }
},
{
  "model": "hotel.room",
  "pk": 14,
  "fields": {
    "category": "Deluxe",
    "bedType": "King Size",
    "adults": 3,
    "children": 0,
    "squareType": 38,
    "number": 206,
    "name_ru": "Сеид Мир Мухаммед Алим-хан",
    "name_en": "SAID EMIR ALIMKHAN",
    "description_ru": "Сеид Мир Мухаммед Алим-хан — номер, посвященный последнему эмиру Бухарского эмирата. Команта с площадью ___ квадратных метров перенесет вас во времена смелого эмира и позволит расслабиться и отдохнуть, словно настоящий правитель!",
    "description_en": "Said Emir AlimKhan is a room dedicated to the last Emir of Bukhara Emirate. The ___ square meter room will take you back to the time of the brave emir and allow you to relax and unwind like a real ruler",
    "numberOfBeds": 2,
    "price": 1120000,
    "historicalImage": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "beRoomType": "014"
  }
},
{
  "model": "hotel.room",
  "pk": 15,
  "fields": {
    "category": "Luxe",
    "bedType": "King Size",
    "adults": 2,
    "children": 2,
    "squareType": 46,
    "number": 304,
    "name_ru": "Абульгази Багадырхан",
    "name_en": "ABULGAZI BAKHODIRKHAN",
    "description_ru": "Абульгази Багадырхан — был хивинским ханом, а также историком и писателем. Номер, посвященный хану, богат самыми лучшими условиями для роскошного отдыха. Выбрав такой номер, вы точно обеспечите для себя идеальное времяпрепровождение.",
    "description_en": "ABULGAZI BAKHODIRKHAN - was a Khan of Khiva as well as a historian and writer. The room dedicated to the khan is rich in the best conditions for a luxurious stay. By choosing such a room, you are sure to ensure a perfect stay for yourself.",
    "numberOfBeds": 2,
    "price": 1950000,
    "historicalImage": "https://silkroadempirehotel.com/media/room_images/SRE_-_312_Amir_Temur_siute_-_4.JPG.1024x1024_q85.jpg",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "015"
  }
},{
  "model": "hotel.room",
  "pk": 16,
  "fields": {
"category": "Luxe",
    "bedType": "Twin",
    "adults": 1,
    "children": 1,
    "squareType": 24,
    "number": 302,
    "name_ru": "Анахита",
    "name_en": "ANAHITA",
    "description_ru": "Номер, посвященный Ардвисуре Анахите, создаст для вас отдых истинных богин! Ведь героиня этого номера была богиней воды и плодородия в иранской мифологии. Невероятное величие покоев перенесет вас в атмосферу древней античности и обеспечат лучшее пребывание в городе Самарканд!",
    "description_en": "The room dedicated to Ardvisura Anahita will create for you the rest of true goddesses! After all, the heroine of this number was the goddess of water and fertility in Iranian mythology. The incredible greatness of the chambers will take you into the atmosphere of ancient antiquity and ensure the best stay in the city of Samarkand! ",
    "numberOfBeds": 2,
    "price": 2700000,
    "historicalImage": "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "012"
  }
},
{
  "model": "hotel.room",
  "pk": 13,
  "fields": {
    "category": "Luxe",
    "bedType": "Twin",
    "adults": 1,
    "children": 0,
    "squareType": 32,
    "number": 303,
    "name_ru": "Вархуман",
    "name_en": "VARHUMAN",
    "description_ru": "Вархуман был царем Согдианы в 7 веке нашей эры. Мы посвятили ему номер с площадью _ квадратных метров, который буквально наполнен историей одного из самого великого царя античности. Уютный и в то же время просторный номер окружит вас отдыхом, который вы точно запомните надолго!",
    "description_en": "Varhuman was the king of Sogdiana in the 7th century. We dedicated to him a room with an area of _ square meters, which is literally filled with the history of one of the greatest kings of antiquity. A cozy and at the same time spacious room will surround you with a vacation that you will definitely remember for a long time!",
    "numberOfBeds": 2,
    "price": 2100000,
    "historicalImage": "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "013"
  }
},
{
  "model": "hotel.room",
  "pk": 14,
  "fields": {
    "category": "Deluxe",
    "bedType": "King Size",
    "adults": 3,
    "children": 0,
    "squareType": 38,
    "number": 206,
    "name_ru": "Сеид Мир Мухаммед Алим-хан",
    "name_en": "SAID EMIR ALIMKHAN",
    "description_ru": "Сеид Мир Мухаммед Алим-хан — номер, посвященный последнему эмиру Бухарского эмирата. Команта с площадью ___ квадратных метров перенесет вас во времена смелого эмира и позволит расслабиться и отдохнуть, словно настоящий правитель!",
    "description_en": "Said Emir AlimKhan is a room dedicated to the last Emir of Bukhara Emirate. The ___ square meter room will take you back to the time of the brave emir and allow you to relax and unwind like a real ruler",
    "numberOfBeds": 2,
    "price": 1120000,
    "historicalImage": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "beRoomType": "014"
  }
},
{
  "model": "hotel.room",
  "pk": 15,
  "fields": {
    "category": "Luxe",
    "bedType": "King Size",
    adults: 1,
    children: 0,
    "squareType": 46,
    "number": 304,
    "name_ru": "Абульгази Багадырхан",
    "name_en": "ABULGAZI BAKHODIRKHAN",
    "description_ru": "Абульгази Багадырхан — был хивинским ханом, а также историком и писателем. Номер, посвященный хану, богат самыми лучшими условиями для роскошного отдыха. Выбрав такой номер, вы точно обеспечите для себя идеальное времяпрепровождение.",
    "description_en": "Kanishka III is the third emperor of the Kushan Kingdom. The ancient history of the ruler allowed us to create a room imbued with his indomitable spirit. The royal chambers will allow you to relax after a busy day, and your stay will be unforgettable. ",
    "numberOfBeds": 2,
    "price": 1950000,
    "historicalImage": "https://silkroadempirehotel.com/media/room_images/SRE_-_312_Amir_Temur_siute_-_4.JPG.1024x1024_q85.jpg",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "015"
  }
},
{
  "model": "hotel.room",
  "pk": 16,
  "fields": {
    "category": "Deluxe",
    "bedType": "King Size",
    "adults": 1,
    "children": 3,
    "squareType": 40,
    "number": 207,
    "name_ru": "Худояр-хан",
    "name_en": "KHUDAYARKHAN",
    "description_ru": "Худояр-хан— одиннадцатый правитель из узбекской династии Мингов в Кокандском ханстве. Номер, с площадью __ квадратных метров выполнен в стиле истинного узбекского хана: каждый уголок пропитан историей и его смелым духом. Почувствуйте себя, словно настоящий полководец и правитель ханства, находясь в этом номере нашего отеля!",
    "description_en": "Khudoyar Khan was the eleventh ruler of the Uzbek Ming dynasty in the Kokand Khanate. This __ square meter room is designed in the style of a true Uzbek khan: every corner is steeped in history and his bold spirit. Feel like a true commander and ruler of the khanate while staying in this room at our hotel!",
    "numberOfBeds": 2,
    "price": 1080000,
    "historicalImage": "https://silkroadempirehotel.com/media/room_images/IMG_8760.JPG.1024x1024_q85.jpg",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "beRoomType": "016"
  }
},
{
  "model": "hotel.room",
  "pk": 17,
  "fields": {
    "category": "Luxe",
    "bedType": "Twin",
    "adults": 3,
    "children": 0,
    "squareType": 35,
    "number": 305,
    "name_ru": "Амир Темур",
    "name_en": "AMIR TEMUR",
    "description_ru": "Амир Темур suite -- люкс, который перенесет вас в атмосферу великого полководца и правителя Средней Азии Амира Темура. Номер с площадью 26 квадратных метра позволит вам почувствовать себя истиннным повелителем и насладиться роскошным отдыхом!",
    "description_en": "The Amir Temur Suite will transport you to the atmosphere of the great commander and ruler of Central Asia, Amir Temur. This 26-square-meter room will make you feel like a true ruler and enjoy a luxurious stay!",
    "numberOfBeds": 2,
    "price": 2350000,
    "historicalImage": "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "017"
  }
},
{
  "model": "hotel.room",
  "pk": 18,
  "fields": {
    "category": "Deluxe",
    "bedType": "Twin",
    "adults": 2,
    "children":2,
    "squareType": 35,
    "number": 208,
    "name_ru": "Бибиханым",
    "name_en": "Bibihanym",
    "description_ru": "Бибиханым — главная жена среднеазиатского правителя Амира Темура с 1370 года. Посвященный ее личности номер, наполнен и пропитан роскошью, в котором жила главная жена правителя. В номер Бибиханым вы сможете почувствовать себя истинной женщиной высшего общества того времени.",
    "description_en": "Bibihanym was the chief wife of the Central Asian ruler Amir Temur from 1370. The room dedicated to her is filled with the luxury of the ruler's chief wife. In Bibihanym's room, you'll feel like a true woman of high society of the time.",
    "numberOfBeds": 2,
    "price": 1000000,
    "historicalImage": "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "shower": true,
    "beRoomType": "018"
  }
},
{
  "model": "hotel.room",
  "pk": 19,
  "fields": {
    "category": "Luxe",
    "bedType": "Twin",
    "adults": 3,
    "children": 0,
    "squareType": 35,
    "number": 306,
    "name_ru": "Мирза Улугбек",
    "name_en": "MIRZO ULUGBEK",
    "description_ru": "Улугбек — это один из знаменитых среднеазиатских государственных деятелей, правитель тюркской державы Тимуридов, сын Шахруха, внук Тамерлана. Номер,с площадью ___ квадратных метро, посвящен выдающемуся математику, астроному, просветителю и поэту своего времени. В номере вы сможете прочувствовать атмосферу самого просвещённого и мудрого деятеля в истории Востока.",
    "description_en": "Mirzo Ulugbek was the chief wife of the Central Asian ruler Amir Temur from 1370. The room dedicated to her is filled with the luxury of the ruler's chief wife. In Bibihanym's room, you'll feel like a true woman of high society of the time.",
    "numberOfBeds": 3,
    "price": 2300000,
    "historicalImage": "https://images.unsplash.com/photo-1612320582827-a95ab2596dbc?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "bath": true,
    "beRoomType": "019"
  }
},
{
  "model": "hotel.room",
  "pk": 20,
  "fields": {
    "category": "Deluxe",
    "bedType": "King Size",
    "adults": 2,
    "children": 0,
    "squareType": 26,
    "number": 209,
    "name_ru": "Сатук Богра-хан",
    "name_en": "SATUQ BUGHRAKHAN",
    "description_ru": "Номер, посвящённый Сатук Богра-хану — это покои с историей с середины 10 века! Он был правителем Кашгара из рода Караханов, а в 942 году смог основать Караханидское государство на тюркской территории. В номере, вас ждет невероятный дух правителя государства, полностью пропитанный многовековой историей! ",
    "description_en": "The room dedicated to Satuq Bugrakhan is a room with a history from the middle of the 10th century! He was the ruler of Kashgar from the Karakhan family, and in 942 he was able to establish a Karakhanid state on the Turkic territory. In the room, you will find the incredible spirit of the ruler of the state, completely imbued with centuries-old history! ",
    "numberOfBeds": 2,
    "price": 1450000,
    "historicalImage": "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=800&q=80",
    "air_conditioner": true,
    "tv": true,
    "wifi": true,
    "mini_bar": true,
    "shower": true,
    "beRoomType": "020"
  }
}
]
